<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>SIPCS.UI</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\SIPCS.BLL\SIPCS.BLL.csproj" />
    <ProjectReference Include="..\SIPCS.Common\SIPCS.Common.csproj" />
  </ItemGroup>
</Project>
